permalink: :year/:month/:title.html
markdown: Kramdown
# Maruku Kramdown rdiscount Redcarpet

img: http://hustlei.qiniudn.com/

# excerpt_separator: "####"

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..2
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  hard_wrap:      false
  header_offset:  1
#  math_engine:  mathjax

  enable_coderay: false

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 5


title : 昨夜星辰
# tagline: 入则孝-出则悌-谨而信-泛爱众-而亲仁
author :
  name : lileilei
  email : hustlei@sina.cn

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
production_url : http://hustlei.tk

safe: false


# 设定文章分组（group）所包含的几个项
group_list:
  PKM
  IT
  Design
  Life


JB :

  ASSET_PATH : false
  IMAGE_PATH : false

  archive_path: /pages/archive.html
  categories_path : /pages/categories.html
  PKMcategories_path : /pages/PKMcategories.html
  ITcategories_path : /pages/ITcategories.html
  DESIGNcategories_path : /pages/Designcategories.html
  LIFEcategories_path : /pages/Lifecategories.html
  tags_path : /pages/tags.html
  messages_path : /pages/messages.html
  music_path : /pages/music.html
  about_path : /pages/about.html
  links_path : /pages/links.html
  weiboxiu_path : /pages/weiboxiu.html
  atom_path : /pages/atom.xml
  rss_path : /pages/rss.xml


  sharing :
    provider : false
    

  
